### PR TITLE
bump Maven Wrapper to 3.6.3

### PR DESCRIPTION
**Pull request by albertocavalcante**
Fixes https://github.com/antlr/Antlr4Formatter/issues/166

### CODE REVIEW

**Comment by albertocavalcante** [comment]
@parrt @teverett can you please review whenever you get a chance? Thanks!

**Comment by parrt** [comment]
Seems ok but I should wait for @teverett

**Comment by teverett** [comment]
sorry @albertocavalcante  and @parrt  I was on holidays all week and was napping in the sunbeam.  I've started the build.

**Comment by teverett** [comment]
@albertocavalcante  thanks!

**Pull request merged**
